// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Blockchain int32

const (
	Blockchain_BTC Blockchain = 0
	Blockchain_ETH Blockchain = 1
	Blockchain_ONT Blockchain = 2
	Blockchain_BNB Blockchain = 3
	Blockchain_EOS Blockchain = 4
	Blockchain_TRX Blockchain = 5
)

var Blockchain_name = map[int32]string{
	0: "BTC",
	1: "ETH",
	2: "ONT",
	3: "BNB",
	4: "EOS",
	5: "TRX",
}

var Blockchain_value = map[string]int32{
	"BTC": 0,
	"ETH": 1,
	"ONT": 2,
	"BNB": 3,
	"EOS": 4,
	"TRX": 5,
}

func (x Blockchain) String() string {
	return proto.EnumName(Blockchain_name, int32(x))
}

func (Blockchain) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

type Script int32

const (
	Script_LUA Script = 0
)

var Script_name = map[int32]string{
	0: "LUA",
}

var Script_value = map[string]int32{
	"LUA": 0,
}

func (x Script) String() string {
	return proto.EnumName(Script_name, int32(x))
}

func (Script) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

type Job struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ConnectSession       string   `protobuf:"bytes,3,opt,name=connectSession,proto3" json:"connectSession,omitempty"`
	Script               Script   `protobuf:"varint,4,opt,name=script,proto3,enum=types.Script" json:"script,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Job) GetConnectSession() string {
	if m != nil {
		return m.ConnectSession
	}
	return ""
}

func (m *Job) GetScript() Script {
	if m != nil {
		return m.Script
	}
	return Script_LUA
}

func (m *Job) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ExecutePlan struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Job                  string   `protobuf:"bytes,3,opt,name=job,proto3" json:"job,omitempty"`
	Tasks                []*Task  `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecutePlan) Reset()         { *m = ExecutePlan{} }
func (m *ExecutePlan) String() string { return proto.CompactTextString(m) }
func (*ExecutePlan) ProtoMessage()    {}
func (*ExecutePlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *ExecutePlan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutePlan.Unmarshal(m, b)
}
func (m *ExecutePlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutePlan.Marshal(b, m, deterministic)
}
func (m *ExecutePlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutePlan.Merge(m, src)
}
func (m *ExecutePlan) XXX_Size() int {
	return xxx_messageInfo_ExecutePlan.Size(m)
}
func (m *ExecutePlan) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutePlan.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutePlan proto.InternalMessageInfo

func (m *ExecutePlan) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ExecutePlan) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExecutePlan) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *ExecutePlan) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

// job execute plan's subtasks
type Task struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Plan                 string   `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	Job                  string   `protobuf:"bytes,3,opt,name=job,proto3" json:"job,omitempty"`
	Script               Script   `protobuf:"varint,4,opt,name=script,proto3,enum=types.Script" json:"script,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetPlan() string {
	if m != nil {
		return m.Plan
	}
	return ""
}

func (m *Task) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *Task) GetScript() Script {
	if m != nil {
		return m.Script
	}
	return Script_LUA
}

func (m *Task) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type TaskInput struct {
	Task                 string   `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskInput) Reset()         { *m = TaskInput{} }
func (m *TaskInput) String() string { return proto.CompactTextString(m) }
func (*TaskInput) ProtoMessage()    {}
func (*TaskInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *TaskInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskInput.Unmarshal(m, b)
}
func (m *TaskInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskInput.Marshal(b, m, deterministic)
}
func (m *TaskInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskInput.Merge(m, src)
}
func (m *TaskInput) XXX_Size() int {
	return xxx_messageInfo_TaskInput.Size(m)
}
func (m *TaskInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskInput.DiscardUnknown(m)
}

var xxx_messageInfo_TaskInput proto.InternalMessageInfo

func (m *TaskInput) GetTask() string {
	if m != nil {
		return m.Task
	}
	return ""
}

func (m *TaskInput) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TaskInput) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type TaskOutput struct {
	Task                 string   `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskOutput) Reset()         { *m = TaskOutput{} }
func (m *TaskOutput) String() string { return proto.CompactTextString(m) }
func (*TaskOutput) ProtoMessage()    {}
func (*TaskOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *TaskOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskOutput.Unmarshal(m, b)
}
func (m *TaskOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskOutput.Marshal(b, m, deterministic)
}
func (m *TaskOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskOutput.Merge(m, src)
}
func (m *TaskOutput) XXX_Size() int {
	return xxx_messageInfo_TaskOutput.Size(m)
}
func (m *TaskOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskOutput.DiscardUnknown(m)
}

var xxx_messageInfo_TaskOutput proto.InternalMessageInfo

func (m *TaskOutput) GetTask() string {
	if m != nil {
		return m.Task
	}
	return ""
}

func (m *TaskOutput) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TaskOutput) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type JobReport struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ConnectSession       string        `protobuf:"bytes,3,opt,name=connectSession,proto3" json:"connectSession,omitempty"`
	Script               Script        `protobuf:"varint,4,opt,name=script,proto3,enum=types.Script" json:"script,omitempty"`
	Data                 []byte        `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	StartTime            string        `protobuf:"bytes,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	StopTime             string        `protobuf:"bytes,7,opt,name=stopTime,proto3" json:"stopTime,omitempty"`
	TaskReports          []*TaskReport `protobuf:"bytes,8,rep,name=taskReports,proto3" json:"taskReports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *JobReport) Reset()         { *m = JobReport{} }
func (m *JobReport) String() string { return proto.CompactTextString(m) }
func (*JobReport) ProtoMessage()    {}
func (*JobReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}

func (m *JobReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobReport.Unmarshal(m, b)
}
func (m *JobReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobReport.Marshal(b, m, deterministic)
}
func (m *JobReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobReport.Merge(m, src)
}
func (m *JobReport) XXX_Size() int {
	return xxx_messageInfo_JobReport.Size(m)
}
func (m *JobReport) XXX_DiscardUnknown() {
	xxx_messageInfo_JobReport.DiscardUnknown(m)
}

var xxx_messageInfo_JobReport proto.InternalMessageInfo

func (m *JobReport) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JobReport) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobReport) GetConnectSession() string {
	if m != nil {
		return m.ConnectSession
	}
	return ""
}

func (m *JobReport) GetScript() Script {
	if m != nil {
		return m.Script
	}
	return Script_LUA
}

func (m *JobReport) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *JobReport) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *JobReport) GetStopTime() string {
	if m != nil {
		return m.StopTime
	}
	return ""
}

func (m *JobReport) GetTaskReports() []*TaskReport {
	if m != nil {
		return m.TaskReports
	}
	return nil
}

type TaskReport struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTime            string   `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	StopTime             string   `protobuf:"bytes,3,opt,name=stopTime,proto3" json:"stopTime,omitempty"`
	Inputs               uint64   `protobuf:"varint,4,opt,name=inputs,proto3" json:"inputs,omitempty"`
	InputBytes           uint64   `protobuf:"varint,5,opt,name=inputBytes,proto3" json:"inputBytes,omitempty"`
	Outputs              uint64   `protobuf:"varint,6,opt,name=outputs,proto3" json:"outputs,omitempty"`
	OutputBytes          uint64   `protobuf:"varint,7,opt,name=outputBytes,proto3" json:"outputBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskReport) Reset()         { *m = TaskReport{} }
func (m *TaskReport) String() string { return proto.CompactTextString(m) }
func (*TaskReport) ProtoMessage()    {}
func (*TaskReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{6}
}

func (m *TaskReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskReport.Unmarshal(m, b)
}
func (m *TaskReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskReport.Marshal(b, m, deterministic)
}
func (m *TaskReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskReport.Merge(m, src)
}
func (m *TaskReport) XXX_Size() int {
	return xxx_messageInfo_TaskReport.Size(m)
}
func (m *TaskReport) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskReport.DiscardUnknown(m)
}

var xxx_messageInfo_TaskReport proto.InternalMessageInfo

func (m *TaskReport) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskReport) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *TaskReport) GetStopTime() string {
	if m != nil {
		return m.StopTime
	}
	return ""
}

func (m *TaskReport) GetInputs() uint64 {
	if m != nil {
		return m.Inputs
	}
	return 0
}

func (m *TaskReport) GetInputBytes() uint64 {
	if m != nil {
		return m.InputBytes
	}
	return 0
}

func (m *TaskReport) GetOutputs() uint64 {
	if m != nil {
		return m.Outputs
	}
	return 0
}

func (m *TaskReport) GetOutputBytes() uint64 {
	if m != nil {
		return m.OutputBytes
	}
	return 0
}

func init() {
	proto.RegisterEnum("types.Blockchain", Blockchain_name, Blockchain_value)
	proto.RegisterEnum("types.Script", Script_name, Script_value)
	proto.RegisterType((*Job)(nil), "types.Job")
	proto.RegisterType((*ExecutePlan)(nil), "types.ExecutePlan")
	proto.RegisterType((*Task)(nil), "types.Task")
	proto.RegisterType((*TaskInput)(nil), "types.TaskInput")
	proto.RegisterType((*TaskOutput)(nil), "types.TaskOutput")
	proto.RegisterType((*JobReport)(nil), "types.JobReport")
	proto.RegisterType((*TaskReport)(nil), "types.TaskReport")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 477 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xd1, 0x6a, 0x13, 0x41,
	0x14, 0xed, 0xee, 0x4e, 0x92, 0xe6, 0xae, 0x86, 0xed, 0x3c, 0xc8, 0x20, 0x22, 0x6b, 0x40, 0x89,
	0x15, 0x52, 0x68, 0xbf, 0xc0, 0xad, 0x05, 0x2d, 0xd2, 0xc8, 0x64, 0x05, 0xf1, 0x6d, 0x76, 0x33,
	0x36, 0x63, 0x92, 0x99, 0x65, 0x67, 0x82, 0xf6, 0xd1, 0x77, 0xbf, 0xcc, 0xaf, 0x92, 0xb9, 0xbb,
	0xd1, 0xb5, 0x54, 0x11, 0xfa, 0xd2, 0xb7, 0x73, 0xcf, 0x99, 0xdc, 0x73, 0xee, 0xbd, 0x61, 0x21,
	0x76, 0x57, 0x95, 0xb4, 0xd3, 0xaa, 0x36, 0xce, 0xd0, 0x1e, 0x16, 0xe3, 0xef, 0x01, 0x44, 0xe7,
	0xa6, 0xa0, 0x23, 0x08, 0xd5, 0x82, 0x05, 0x69, 0x30, 0x19, 0xf2, 0x50, 0x2d, 0x28, 0x05, 0xa2,
	0xc5, 0x46, 0xb2, 0x10, 0x19, 0xc4, 0xf4, 0x19, 0x8c, 0x4a, 0xa3, 0xb5, 0x2c, 0xdd, 0x5c, 0x5a,
	0xab, 0x8c, 0x66, 0x11, 0xaa, 0xd7, 0x58, 0xfa, 0x14, 0xfa, 0xb6, 0xac, 0x55, 0xe5, 0x18, 0x49,
	0x83, 0xc9, 0xe8, 0xf8, 0xfe, 0xb4, 0x31, 0x9e, 0x23, 0xc9, 0x5b, 0xd1, 0x5b, 0x2c, 0x84, 0x13,
	0xac, 0x97, 0x06, 0x93, 0x7b, 0x1c, 0xf1, 0xf8, 0x13, 0xc4, 0x67, 0x5f, 0x65, 0xb9, 0x75, 0xf2,
	0xdd, 0x5a, 0xe8, 0xff, 0x4a, 0x95, 0x40, 0xf4, 0xd9, 0x14, 0x6d, 0x14, 0x0f, 0xe9, 0x13, 0xe8,
	0x39, 0x61, 0x57, 0x96, 0x91, 0x34, 0x9a, 0xc4, 0xc7, 0x71, 0x6b, 0x9f, 0x0b, 0xbb, 0xe2, 0x8d,
	0x32, 0xfe, 0x02, 0xc4, 0x97, 0x37, 0x19, 0x54, 0x6b, 0xa1, 0x77, 0x06, 0x1e, 0xdf, 0x60, 0x70,
	0x8b, 0x01, 0x4f, 0x61, 0xe8, 0x8d, 0xdf, 0xe8, 0x6a, 0x8b, 0x0f, 0x7c, 0x9c, 0xd6, 0x1f, 0x71,
	0x9b, 0xc8, 0xfb, 0x93, 0x5d, 0x22, 0x6c, 0x12, 0x75, 0x9a, 0xbc, 0x02, 0xf0, 0x4d, 0x66, 0x5b,
	0x77, 0x9b, 0x2e, 0xdf, 0x42, 0x18, 0x9e, 0x9b, 0x82, 0xcb, 0xca, 0xd4, 0xee, 0x8e, 0xfc, 0x01,
	0xe8, 0x23, 0x18, 0x5a, 0x27, 0x6a, 0x97, 0xab, 0x8d, 0x64, 0x7d, 0xec, 0xfe, 0x9b, 0xa0, 0x0f,
	0x61, 0xdf, 0x3a, 0x53, 0xa1, 0x38, 0x40, 0xf1, 0x57, 0x4d, 0x4f, 0x20, 0xf6, 0xa3, 0x37, 0xe3,
	0x58, 0xb6, 0x8f, 0xb7, 0x3f, 0xe8, 0xde, 0x1e, 0x15, 0xde, 0x7d, 0x35, 0xfe, 0x11, 0x34, 0xab,
	0xfc, 0xcb, 0x12, 0xfe, 0x48, 0x13, 0xfe, 0x2b, 0x4d, 0x74, 0x2d, 0xcd, 0x03, 0xe8, 0x2b, 0x7f,
	0x63, 0x8b, 0x2b, 0x20, 0xbc, 0xad, 0xe8, 0x63, 0x00, 0x44, 0xd9, 0x95, 0x93, 0x16, 0x27, 0x27,
	0xbc, 0xc3, 0x50, 0x06, 0x03, 0x83, 0x67, 0xb5, 0x38, 0x3d, 0xe1, 0xbb, 0x92, 0xa6, 0x10, 0x37,
	0xb0, 0xf9, 0xe9, 0x00, 0xd5, 0x2e, 0x75, 0x98, 0x01, 0x64, 0x6b, 0x53, 0xae, 0xca, 0xa5, 0x50,
	0x9a, 0x0e, 0x20, 0xca, 0xf2, 0xd3, 0x64, 0xcf, 0x83, 0xb3, 0xfc, 0x75, 0x12, 0x78, 0x30, 0xbb,
	0xc8, 0x93, 0x10, 0xa5, 0x8b, 0x2c, 0x89, 0x50, 0x9a, 0xcd, 0x13, 0xe2, 0x41, 0xce, 0x3f, 0x24,
	0xbd, 0xc3, 0x03, 0xe8, 0x37, 0x57, 0xf2, 0xd4, 0xdb, 0xf7, 0x2f, 0x93, 0xbd, 0xec, 0xc5, 0xc7,
	0xe7, 0x97, 0xca, 0x2d, 0xb7, 0xc5, 0xb4, 0x34, 0x9b, 0xa3, 0xc2, 0x3b, 0x28, 0x6d, 0xd5, 0xe5,
	0xd2, 0x35, 0x85, 0x75, 0xb5, 0x14, 0x9b, 0x23, 0x5c, 0x74, 0xd1, 0xc7, 0xaf, 0xcb, 0xc9, 0xcf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xdb, 0x00, 0x99, 0x6c, 0x04, 0x00, 0x00,
}
