// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Blockchain int32

const (
	Blockchain_BTC Blockchain = 0
	Blockchain_ETH Blockchain = 1
	Blockchain_ONT Blockchain = 2
	Blockchain_BNB Blockchain = 3
	Blockchain_EOS Blockchain = 4
	Blockchain_TRX Blockchain = 5
)

var Blockchain_name = map[int32]string{
	0: "BTC",
	1: "ETH",
	2: "ONT",
	3: "BNB",
	4: "EOS",
	5: "TRX",
}

var Blockchain_value = map[string]int32{
	"BTC": 0,
	"ETH": 1,
	"ONT": 2,
	"BNB": 3,
	"EOS": 4,
	"TRX": 5,
}

func (x Blockchain) String() string {
	return proto.EnumName(Blockchain_name, int32(x))
}

func (Blockchain) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

type Worker int32

const (
	Worker_LUA Worker = 0
)

var Worker_name = map[int32]string{
	0: "LUA",
}

var Worker_value = map[string]int32{
	"LUA": 0,
}

func (x Worker) String() string {
	return proto.EnumName(Worker_name, int32(x))
}

func (Worker) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

type Job struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pipelines            []*Task  `protobuf:"bytes,2,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetPipelines() []*Task {
	if m != nil {
		return m.Pipelines
	}
	return nil
}

type Task struct {
	Test                 string   `protobuf:"bytes,1,opt,name=test,proto3" json:"test,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetTest() string {
	if m != nil {
		return m.Test
	}
	return ""
}

func init() {
	proto.RegisterEnum("types.Blockchain", Blockchain_name, Blockchain_value)
	proto.RegisterEnum("types.Worker", Worker_name, Worker_value)
	proto.RegisterType((*Job)(nil), "types.Job")
	proto.RegisterType((*Task)(nil), "types.Task")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xd7, 0xa4, 0x9b, 0xec, 0x15, 0x24, 0xe6, 0x34, 0x3c, 0x8d, 0x9d, 0xb6, 0x09, 0x1d,
	0xe8, 0x17, 0xd0, 0x88, 0x20, 0x22, 0x1b, 0xd4, 0x88, 0xe2, 0xad, 0xe9, 0xc2, 0xfa, 0xe8, 0xda,
	0x84, 0x24, 0x1e, 0xfc, 0xf6, 0x92, 0x54, 0xf0, 0xf6, 0xfb, 0xff, 0x7f, 0x24, 0xef, 0x3d, 0x28,
	0xc2, 0x8f, 0xd5, 0xbe, 0xb4, 0xce, 0x04, 0xc3, 0xa7, 0x29, 0xac, 0xee, 0x81, 0xbe, 0x18, 0xc5,
	0x2f, 0x81, 0xe0, 0x71, 0x91, 0x2d, 0xb3, 0xf5, 0xbc, 0x22, 0x78, 0xe4, 0x1b, 0x98, 0x5b, 0xb4,
	0xfa, 0x8c, 0x83, 0xf6, 0x0b, 0xb2, 0xa4, 0xeb, 0xe2, 0xb6, 0x28, 0xc7, 0xe7, 0xb2, 0xf6, 0x5d,
	0xf5, 0x6f, 0x57, 0xd7, 0x90, 0xc7, 0x8a, 0x73, 0xc8, 0x83, 0xf6, 0xe1, 0xef, 0x93, 0xc4, 0x5b,
	0x01, 0x20, 0xce, 0xa6, 0xe9, 0x9a, 0xb6, 0xc6, 0x81, 0x5f, 0x00, 0x15, 0xf2, 0x91, 0x4d, 0x22,
	0x3c, 0xc9, 0x67, 0x96, 0x45, 0x38, 0xec, 0x25, 0x23, 0x49, 0xed, 0x05, 0xa3, 0x49, 0x1d, 0xde,
	0x58, 0x1e, 0x41, 0x56, 0x9f, 0x6c, 0xba, 0xbd, 0x82, 0xd9, 0x87, 0x71, 0x9d, 0x76, 0xb1, 0x7a,
	0x7d, 0x7f, 0x60, 0x13, 0x71, 0xf3, 0xb5, 0x39, 0x61, 0x68, 0xbf, 0x55, 0xd9, 0x98, 0x7e, 0xa7,
	0xe2, 0x04, 0x1c, 0x3c, 0x9e, 0xda, 0x30, 0x06, 0x1f, 0x9c, 0xae, 0xfb, 0x5d, 0xda, 0x57, 0xcd,
	0xd2, 0xbd, 0x77, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc5, 0xb1, 0xca, 0x07, 0xfe, 0x00, 0x00,
	0x00,
}
