// Code generated by protoc-gen-go. DO NOT EDIT.
// source: probe.proto

package probe

import (
	context "context"
	fmt "fmt"
	types "github.com/blockinsight/blockstream/types"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JobRequest struct {
	Blockchain           types.Blockchain `protobuf:"varint,1,opt,name=blockchain,proto3,enum=types.Blockchain" json:"blockchain,omitempty"`
	ChainId              string           `protobuf:"bytes,2,opt,name=chainId,proto3" json:"chainId,omitempty"`
	RemoteUrl            string           `protobuf:"bytes,3,opt,name=remoteUrl,proto3" json:"remoteUrl,omitempty"`
	Offset               uint64           `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64            `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *JobRequest) Reset()         { *m = JobRequest{} }
func (m *JobRequest) String() string { return proto.CompactTextString(m) }
func (*JobRequest) ProtoMessage()    {}
func (*JobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8cc8551cf1a5c4f, []int{0}
}

func (m *JobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobRequest.Unmarshal(m, b)
}
func (m *JobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobRequest.Marshal(b, m, deterministic)
}
func (m *JobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobRequest.Merge(m, src)
}
func (m *JobRequest) XXX_Size() int {
	return xxx_messageInfo_JobRequest.Size(m)
}
func (m *JobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobRequest proto.InternalMessageInfo

func (m *JobRequest) GetBlockchain() types.Blockchain {
	if m != nil {
		return m.Blockchain
	}
	return types.Blockchain_BTC
}

func (m *JobRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *JobRequest) GetRemoteUrl() string {
	if m != nil {
		return m.RemoteUrl
	}
	return ""
}

func (m *JobRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *JobRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type JobResponse struct {
	Block                []byte   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobResponse) Reset()         { *m = JobResponse{} }
func (m *JobResponse) String() string { return proto.CompactTextString(m) }
func (*JobResponse) ProtoMessage()    {}
func (*JobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8cc8551cf1a5c4f, []int{1}
}

func (m *JobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobResponse.Unmarshal(m, b)
}
func (m *JobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobResponse.Marshal(b, m, deterministic)
}
func (m *JobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobResponse.Merge(m, src)
}
func (m *JobResponse) XXX_Size() int {
	return xxx_messageInfo_JobResponse.Size(m)
}
func (m *JobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobResponse proto.InternalMessageInfo

func (m *JobResponse) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

func init() {
	proto.RegisterType((*JobRequest)(nil), "probe.JobRequest")
	proto.RegisterType((*JobResponse)(nil), "probe.JobResponse")
}

func init() { proto.RegisterFile("probe.proto", fileDescriptor_f8cc8551cf1a5c4f) }

var fileDescriptor_f8cc8551cf1a5c4f = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x59, 0xdb, 0x54, 0x32, 0x11, 0xa1, 0x8b, 0xc8, 0x52, 0x3c, 0x84, 0x7a, 0x89, 0x08,
	0xa9, 0x56, 0xaf, 0x5e, 0xea, 0xc9, 0x9e, 0x64, 0xc1, 0x8b, 0xb7, 0x6c, 0x9c, 0x36, 0xc1, 0x26,
	0x13, 0x77, 0x27, 0x07, 0x3f, 0x90, 0xdf, 0x53, 0xba, 0xab, 0x6d, 0x6e, 0xf3, 0x7b, 0xf3, 0x87,
	0x37, 0x0f, 0x92, 0xce, 0x92, 0xc1, 0xbc, 0xb3, 0xc4, 0x24, 0x23, 0x0f, 0xb3, 0x84, 0xbf, 0x3b,
	0x74, 0x41, 0x9b, 0xff, 0x08, 0x80, 0x35, 0x19, 0x8d, 0x5f, 0x3d, 0x3a, 0x96, 0xf7, 0x00, 0x66,
	0x47, 0xe5, 0x67, 0x59, 0x15, 0x75, 0xab, 0x44, 0x2a, 0xb2, 0xf3, 0xe5, 0x34, 0x0f, 0x0b, 0xab,
	0x43, 0x43, 0x0f, 0x86, 0xa4, 0x82, 0x53, 0x5f, 0xbc, 0x7c, 0xa8, 0x93, 0x54, 0x64, 0xb1, 0xfe,
	0x47, 0x79, 0x05, 0xb1, 0xc5, 0x86, 0x18, 0xdf, 0xec, 0x4e, 0x8d, 0x7c, 0xef, 0x28, 0xc8, 0x4b,
	0x98, 0xd0, 0x66, 0xe3, 0x90, 0xd5, 0x38, 0x15, 0xd9, 0x58, 0xff, 0x91, 0xbc, 0x80, 0xa8, 0xa4,
	0xbe, 0x65, 0x15, 0xa5, 0x22, 0x1b, 0xe9, 0x00, 0xf3, 0x6b, 0x48, 0xbc, 0x4d, 0xd7, 0x51, 0xeb,
	0x70, 0x3f, 0xe4, 0x2d, 0x78, 0x8b, 0x67, 0x3a, 0xc0, 0xf2, 0x09, 0xa2, 0xd7, 0xfd, 0x8b, 0xf2,
	0x11, 0xe2, 0x67, 0x8b, 0x05, 0xe3, 0x9a, 0x8c, 0x9c, 0xe6, 0x21, 0x84, 0xe3, 0x9b, 0x33, 0x39,
	0x94, 0xc2, 0xc9, 0x3b, 0xb1, 0xba, 0x7d, 0xbf, 0xd9, 0xd6, 0x5c, 0xf5, 0x26, 0x2f, 0xa9, 0x59,
	0xf8, 0x93, 0x75, 0xeb, 0xea, 0x6d, 0xc5, 0x01, 0x1c, 0x5b, 0x2c, 0x9a, 0x85, 0x5f, 0x35, 0x13,
	0x9f, 0xdf, 0xc3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x6a, 0x80, 0xee, 0x62, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProbeClient is the client API for Probe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProbeClient interface {
	CreateJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (Probe_CreateJobClient, error)
}

type probeClient struct {
	cc *grpc.ClientConn
}

func NewProbeClient(cc *grpc.ClientConn) ProbeClient {
	return &probeClient{cc}
}

func (c *probeClient) CreateJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (Probe_CreateJobClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Probe_serviceDesc.Streams[0], "/probe.Probe/CreateJob", opts...)
	if err != nil {
		return nil, err
	}
	x := &probeCreateJobClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Probe_CreateJobClient interface {
	Recv() (*JobResponse, error)
	grpc.ClientStream
}

type probeCreateJobClient struct {
	grpc.ClientStream
}

func (x *probeCreateJobClient) Recv() (*JobResponse, error) {
	m := new(JobResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProbeServer is the server API for Probe service.
type ProbeServer interface {
	CreateJob(*JobRequest, Probe_CreateJobServer) error
}

func RegisterProbeServer(s *grpc.Server, srv ProbeServer) {
	s.RegisterService(&_Probe_serviceDesc, srv)
}

func _Probe_CreateJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProbeServer).CreateJob(m, &probeCreateJobServer{stream})
}

type Probe_CreateJobServer interface {
	Send(*JobResponse) error
	grpc.ServerStream
}

type probeCreateJobServer struct {
	grpc.ServerStream
}

func (x *probeCreateJobServer) Send(m *JobResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Probe_serviceDesc = grpc.ServiceDesc{
	ServiceName: "probe.Probe",
	HandlerType: (*ProbeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateJob",
			Handler:       _Probe_CreateJob_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "probe.proto",
}
