// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package storage

import (
	context "context"
	fmt "fmt"
	types "github.com/blockinsight/blockstream/types"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PutRequest struct {
	Row                  *types.TaskOutput `protobuf:"bytes,1,opt,name=row,proto3" json:"row,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetRow() *types.TaskOutput {
	if m != nil {
		return m.Row
	}
	return nil
}

type PutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}

func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

type PullRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                uint64   `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullRequest) Reset()         { *m = PullRequest{} }
func (m *PullRequest) String() string { return proto.CompactTextString(m) }
func (*PullRequest) ProtoMessage()    {}
func (*PullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2}
}

func (m *PullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequest.Unmarshal(m, b)
}
func (m *PullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequest.Marshal(b, m, deterministic)
}
func (m *PullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequest.Merge(m, src)
}
func (m *PullRequest) XXX_Size() int {
	return xxx_messageInfo_PullRequest.Size(m)
}
func (m *PullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequest proto.InternalMessageInfo

func (m *PullRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PullRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *PullRequest) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type PullResponse struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Offset               uint64            `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Output               *types.TaskOutput `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PullResponse) Reset()         { *m = PullResponse{} }
func (m *PullResponse) String() string { return proto.CompactTextString(m) }
func (*PullResponse) ProtoMessage()    {}
func (*PullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{3}
}

func (m *PullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullResponse.Unmarshal(m, b)
}
func (m *PullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullResponse.Marshal(b, m, deterministic)
}
func (m *PullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullResponse.Merge(m, src)
}
func (m *PullResponse) XXX_Size() int {
	return xxx_messageInfo_PullResponse.Size(m)
}
func (m *PullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullResponse proto.InternalMessageInfo

func (m *PullResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PullResponse) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *PullResponse) GetOutput() *types.TaskOutput {
	if m != nil {
		return m.Output
	}
	return nil
}

func init() {
	proto.RegisterType((*PutRequest)(nil), "storage.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "storage.PutResponse")
	proto.RegisterType((*PullRequest)(nil), "storage.PullRequest")
	proto.RegisterType((*PullResponse)(nil), "storage.PullResponse")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb) }

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xd9, 0xa4, 0xa6, 0x38, 0xb1, 0x82, 0x63, 0x94, 0x90, 0x53, 0x59, 0x2f, 0xf1, 0x12,
	0x34, 0xe2, 0xaf, 0xf0, 0x60, 0x59, 0xfd, 0x03, 0xd1, 0x6e, 0xa5, 0x58, 0x3a, 0x6b, 0x76, 0x16,
	0xf1, 0xdf, 0x4b, 0x76, 0x12, 0xa8, 0xe2, 0xc1, 0xe3, 0x7b, 0x33, 0xf3, 0xed, 0xdb, 0x07, 0x0b,
	0xcf, 0xd4, 0x77, 0x6f, 0xb6, 0x71, 0x3d, 0x31, 0xe1, 0x7c, 0x94, 0x55, 0xce, 0x5f, 0xce, 0x7a,
	0x71, 0xf5, 0x2d, 0xc0, 0x2a, 0xb0, 0xb1, 0x1f, 0xc1, 0x7a, 0xc6, 0x2b, 0x48, 0x7b, 0xfa, 0x2c,
	0xd5, 0x52, 0xd5, 0x79, 0x7b, 0xd6, 0xc8, 0xe2, 0x73, 0xe7, 0xdf, 0x1f, 0x03, 0xbb, 0xc0, 0x66,
	0x98, 0xea, 0x05, 0xe4, 0xf1, 0xc4, 0x3b, 0xda, 0x7b, 0xab, 0x1f, 0x06, 0xb9, 0xdb, 0x4d, 0x88,
	0x53, 0x48, 0xb6, 0xeb, 0x48, 0x38, 0x36, 0xc9, 0x76, 0x8d, 0x97, 0x90, 0xd1, 0x66, 0xe3, 0x2d,
	0x97, 0xc9, 0x52, 0xd5, 0x33, 0x33, 0x2a, 0x2c, 0xe0, 0xe8, 0x95, 0xc2, 0x9e, 0xcb, 0x34, 0xda,
	0x22, 0x74, 0x07, 0x27, 0x02, 0x13, 0xf8, 0xbf, 0x69, 0xd7, 0x90, 0x51, 0x8c, 0x18, 0x71, 0x7f,
	0x66, 0x1f, 0x17, 0x5a, 0x86, 0xf9, 0x93, 0x34, 0x81, 0xf7, 0x30, 0x1b, 0x5e, 0xc3, 0xa2, 0x99,
	0xaa, 0x3a, 0xf8, 0x49, 0x75, 0xf1, 0xcb, 0x95, 0x48, 0x37, 0x0a, 0x5b, 0x48, 0x57, 0x81, 0xf1,
	0xfc, 0x60, 0x3e, 0x35, 0x58, 0x15, 0x3f, 0x4d, 0xb9, 0xa9, 0xd5, 0x4b, 0x16, 0xeb, 0xbe, 0xfb,
	0x0e, 0x00, 0x00, 0xff, 0xff, 0x91, 0x83, 0x33, 0xb1, 0x95, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageClient interface {
	Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (Storage_PullClient, error)
	Put(ctx context.Context, opts ...grpc.CallOption) (Storage_PutClient, error)
}

type storageClient struct {
	cc *grpc.ClientConn
}

func NewStorageClient(cc *grpc.ClientConn) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (Storage_PullClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Storage_serviceDesc.Streams[0], "/storage.Storage/Pull", opts...)
	if err != nil {
		return nil, err
	}
	x := &storagePullClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Storage_PullClient interface {
	Recv() (*PullResponse, error)
	grpc.ClientStream
}

type storagePullClient struct {
	grpc.ClientStream
}

func (x *storagePullClient) Recv() (*PullResponse, error) {
	m := new(PullResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageClient) Put(ctx context.Context, opts ...grpc.CallOption) (Storage_PutClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Storage_serviceDesc.Streams[1], "/storage.Storage/Put", opts...)
	if err != nil {
		return nil, err
	}
	x := &storagePutClient{stream}
	return x, nil
}

type Storage_PutClient interface {
	Send(*PutRequest) error
	CloseAndRecv() (*PutResponse, error)
	grpc.ClientStream
}

type storagePutClient struct {
	grpc.ClientStream
}

func (x *storagePutClient) Send(m *PutRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storagePutClient) CloseAndRecv() (*PutResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PutResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StorageServer is the server API for Storage service.
type StorageServer interface {
	Pull(*PullRequest, Storage_PullServer) error
	Put(Storage_PutServer) error
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_Pull_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServer).Pull(m, &storagePullServer{stream})
}

type Storage_PullServer interface {
	Send(*PullResponse) error
	grpc.ServerStream
}

type storagePullServer struct {
	grpc.ServerStream
}

func (x *storagePullServer) Send(m *PullResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Storage_Put_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServer).Put(&storagePutServer{stream})
}

type Storage_PutServer interface {
	SendAndClose(*PutResponse) error
	Recv() (*PutRequest, error)
	grpc.ServerStream
}

type storagePutServer struct {
	grpc.ServerStream
}

func (x *storagePutServer) SendAndClose(m *PutResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storagePutServer) Recv() (*PutRequest, error) {
	m := new(PutRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storage.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Pull",
			Handler:       _Storage_Pull_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Put",
			Handler:       _Storage_Put_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "storage.proto",
}
